### PR TITLE
SEP-24: add optional SEP-9 fields to deposit and withdrawal

### PR DESCRIPTION
**Pull request by quietbits**
- Created `extra` param in store for various things (like SEP-9 fields)
- No validation or formatting added to the SEP-9 fields (submitted as entered)
- Updated SEP-24 deposit and withdrawal flow to accept SEP-9 fields if provided

image

### CODE REVIEW

**Comment by quietbits** [comment]
Added memo

image

**Comment by JakeUrban** [comment]
Hey Iveta, can you describe the application logic here? How does the demo wallet know if the anchor accepts SEP-9 fields in the deposit and withdraw requests, and how does it know which fields it can provide? Does the user of the demo wallet interactively select the fields they want to provide?

**Comment by quietbits** [comment]
Hey, @JakeUrban ! As we discussed offline, we'll allow users to select SEP-9 fields to submit dynamically, as you suggested above.

**Review by JakeUrban — APPROVED** [review]
Looks great!

**Review by Ifropc — APPROVED** [review]
Looks great, thanks @quietbits !

**Pull request merged**
