### PR TITLE
SEP-6 deposit updates

### PR DESCRIPTION
**Pull request by quietbits**
- Add amount input
- Show min/max amount
- Button to trigger polling action (it was automatic before)

### CODE REVIEW

**Comment by shanzzam** [comment]
Testing this: I'm getting the KYC collection popup every time. Aren't I supposed to get this only the first time?

**Comment by quietbits** [comment]
I'm getting KYC every time now as well, I'm pretty sure it wasn't happening last week. 🤔 I'm seeing the same on the release PR preview. @JakeUrban has anything changed on the backend?

**Comment by JakeUrban** [comment]
I recently added support for [SEP-12 property verification](https://github.com/stellar/stellar-protocol/commit/2d46fe87fa9aa512610078eda51dc52573ed754b#), here's the [Polaris commit](https://github.com/stellar/django-polaris/commit/448e012520895e1d81b31da634c103eb83509d9d).

How does the demo wallet determine which fields need to be collected?

**Comment by quietbits** [comment]
@JakeUrban We're checking if there are any `fields` returned for `/customer`. Should we be checking the status of each field returned? Before this update, the fields were not returned at all if they didn't need to be submitted.

@shanzzam Should we create a separate issue for this?

**Comment by JakeUrban** [comment]
I'm realizing there was some ambiguity introduced with the SEP-12 change, so I'm making an issuing on the stellar-protocol repo to discuss potential clarifications.

For now, the demo wallet should first check if the customer's status is `NEEDS_INFO`. If it is, then information needs to be collected, otherwise the anchor is either processing info or the customer was rejected. 

When the customer's status is `NEEDS_INFO`, we should check for the presence of field-level `status` values. `NOT_PROVIDED` fields should be collected in the modal, and fields without `status` values can be assumed to be `NOT_PROVIDED`.

**Comment by shanzzam** [comment]
This looks good to me!

**Review by piyalbasu — APPROVED** [review]

**Pull request merged**
